### ISSUE TITLE
This page isn’t working 192.168.1.23 is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by rwb99** [mitchellurgero/mailinabox_dynamic_dns_script#2]
i get this error from /api.php when i try to submit a sub domain

**Comment by mitchellurgero** [comment]
Can you please provide logs?

**Comment by rwb99** [comment]
#1 {main}
  thrown in /var/www/html5/api.php on line 92" while reading response header from upstream, client: 192.168.1.15, server: x.x.x.x, request: "POST /api.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.1.23:1114", referrer: "http://192.168.1.23:1114/dashboard.php"
2020/04/22 14:29:40 [error] 12866#12866: *33 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html5/api.php:92
Stack trace:
#0 /var/www/html5/api.php(39): curl(Array)
#1 {main}
  thrown in /var/www/html5/api.php on line 92" while reading response header from upstream, client: 192.168.1.15, server: x.x.x.x, request: "POST /api.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.1.23:1114", referrer: "http://192.168.1.23:1114/dashboard.php"
2020/04/22 14:30:29 [error] 12866#12866: *33 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html5/api.php:92
Stack trace:
#0 /var/www/html5/api.php(39): curl(Array)
#1 {main}
  thrown in /var/www/html5/api.php on line 92" while reading response header from upstream, client: 192.168.1.15, server: x.x.x.x, request: "POST /api.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.1.23:1114", referrer: "http://192.168.1.23:1114/dashboard.php"

**Comment by mitchellurgero** [comment]
You need to install php-curl.

**Comment by rwb99** [comment]
i have already installed it.

im newish to php so i may not have this setup right. im using nginx and this is my php config

 location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
                # With php-cgi (or other tcp sockets):
                #fastcgi_pass 127.0.0.1:9000;
        }

**Comment by mitchellurgero** [comment]
If you run `php -m` does it display the curl module is enabled?

**Comment by rwb99** [comment]
yep. it does

**Comment by mitchellurgero** [comment]
Your logs say otherwise, I would check the php config file that nginx (fast-cgi) uses

**Comment by rwb99** [comment]
i switched to Apache so its working but now i'm getting "ERROR: That IP Address is not valid! Please try again!". Like that other guy. I've tried 1.1.1.1, 8.8.8.8, 192.168.1.69, and my own public ip
